import gradio as gr

PERSONA_THEME = gr.themes.Soft(
    primary_hue="slate",
    secondary_hue="stone",
    neutral_hue="stone",
    font=gr.themes.GoogleFont("IBM Plex Sans"),
    font_mono=gr.themes.GoogleFont("IBM Plex Mono"),
).set(
    body_background_fill="#f3efe7",
    body_background_fill_dark="#12151a",
    background_fill_primary="#f3efe7",
    background_fill_primary_dark="#12151a",
    background_fill_secondary="#fffcf7",
    background_fill_secondary_dark="#1a1f27",
    block_background_fill="#fffcf7",
    block_background_fill_dark="#1a1f27",
    block_border_width="0px",
    block_shadow="0 18px 50px rgba(27, 42, 65, 0.07)",
    block_label_text_color="#1b2a41",
    block_title_text_color="#1b2a41",
    button_primary_background_fill="#1b2a41",
    button_primary_background_fill_hover="#243656",
    button_primary_background_fill_dark="#cfc3ae",
    button_primary_text_color="#fffcf7",
    button_primary_text_color_dark="#1b2a41",
    button_primary_border_color="#1b2a41",
    button_secondary_background_fill="#efe8dc",
    button_secondary_text_color="#1b2a41",
    input_background_fill="#ffffff",
    input_border_color="#e4dcd0",
    input_shadow="none",
    border_color_accent="#1b2a41",
    link_text_color="#1b2a41",
)
